# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mpboost <- function(N1, N2, MTI = 2L) {
    ## checking the input
    if (N1 > 0 & N1%%1 == 0 & N2 > 0 & N2%%1 == 0 & MTI > 0 & MTI%%1 == 0)
        .Call(`_MPBoost_mpboost`, N1, N2, MTI)
    else
        stop("None of 'N1', 'N2' or 'MTI' can be nonpositive or have a fractional part")        
}
